"""empty message

Revision ID: 007f6c5c17c3
Revises: c7ac341880cf
Create Date: 2021-06-18 21:23:16.131592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '007f6c5c17c3'
down_revision = 'c7ac341880cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acs', sa.Column('horas', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('acs', 'horas')
    # ### end Alembic commands ###
